//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class qry_ProjekteASP
    {
        public int ENTRY_No { get; set; }
        public string TITEL_PROJEKT_FILM { get; set; }
        public Nullable<System.DateTime> DATUM_ANGEBOT { get; set; }
        public Nullable<System.DateTime> aktualisiert { get; set; }
        public string Rating { get; set; }
        public int StatusNr { get; set; }
        public string Status2 { get; set; }
        public int xabgelehnt { get; set; }
        public string Land { get; set; }
        public int AnbieterNr { get; set; }
        public string Kontakt { get; set; }
        public string Firma { get; set; }
        public string Anb { get; set; }
        public Nullable<bool> AnbieterAF { get; set; }
        public Nullable<int> zuständig { get; set; }
        public string Bearbeiter { get; set; }
        public Nullable<int> RegisseurNr { get; set; }
        public string Regie { get; set; }
        public string Werke { get; set; }
        public string Produzenten { get; set; }
        public string Produktionsfirma { get; set; }
        public string Script_Buch { get; set; }
        public string Drehbeginn { get; set; }
        public string Lieferbar { get; set; }
        public string US_Release { get; set; }
        public string Geschichte { get; set; }
        public string Besetzung { get; set; }
        public string Sonstiges { get; set; }
        public string Beurteilung { get; set; }
        public string Budget { get; set; }
        public string Asking { get; set; }
        public string Angebot { get; set; }
        public bool Festival_akt { get; set; }
        public string Anfangsbuchstabe { get; set; }
        public string Status { get; set; }
    }
}
