//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class qry_ProjekteIndex
    {
        public int ENTRY_No { get; set; }
        public string Titel { get; set; }
        public int ProjektartNr { get; set; }
        public string Projektart { get; set; }
        public string Rating { get; set; }
        public int BearbeiterNr { get; set; }
        public string zuständig { get; set; }
        public string Status2 { get; set; }
        public bool Festival_akt { get; set; }
        public int AnbieterNr { get; set; }
        public string Anbieter { get; set; }
        public Nullable<bool> AnbieterAF { get; set; }
        public Nullable<System.DateTime> DATUM_ANGEBOT { get; set; }
        public string Land { get; set; }
        public string Regie { get; set; }
        public int StatusNr { get; set; }
        public string Status { get; set; }
        public int LENr { get; set; }
        public string Lektoratseinschaetzung { get; set; }
        public string Originaltitel { get; set; }
        public string Landsuche { get; set; }
        public bool Prioliste { get; set; }
        public string RegieMatchname { get; set; }
        public System.DateTime aufgenommen_am { get; set; }
        public bool Sichtung { get; set; }
        public bool Produktionsliste { get; set; }
        public int BearbeiterNr2 { get; set; }
        public int AnbieterNr2 { get; set; }
        public string Anbieter2 { get; set; }
    }
}
