//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BlobProjekte
    {
        public int EntryNo { get; set; }
        public byte[] Lektorat { get; set; }
        public byte[] Vergleichsfilm { get; set; }
        public string LektoratFileName { get; set; }
        public string VergleichsfilmFileName { get; set; }
    
        public virtual tbl_Projekte tbl_Projekte { get; set; }
    }
}
