//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProjektPersonRel
    {
        public int ID { get; set; }
        public int EntryNo { get; set; }
        public int PersonNr { get; set; }
        public Nullable<int> Prio { get; set; }
        public int FunktionNr { get; set; }
        public bool ersetzt { get; set; }
    
        public virtual tbl_Personen tbl_Personen { get; set; }
        public virtual tbl_Funktionen tbl_Funktionen { get; set; }
        public virtual tbl_Projekte tbl_Projekte { get; set; }
    }
}
