//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ProjektFirmaRel
    {
        public int ID { get; set; }
        public int EntryNo { get; set; }
        public int FirmaNr { get; set; }
        public Nullable<int> Prio { get; set; }
    
        public virtual tbl_Firmen tbl_Firmen { get; set; }
        public virtual tbl_Projekte tbl_Projekte { get; set; }
    }
}
