//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Anbieter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Anbieter()
        {
            this.tbl_Projekte = new HashSet<tbl_Projekte>();
            this.tbl_Projekte1 = new HashSet<tbl_Projekte>();
        }
    
        public int AnbieterNr { get; set; }
        public string Kürzel { get; set; }
        public string Kontaktperson { get; set; }
        public int zuständig { get; set; }
        public bool AnbieterAF { get; set; }
    
        public virtual tbl_Bearbeiter tbl_Bearbeiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Projekte> tbl_Projekte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Projekte> tbl_Projekte1 { get; set; }
    }
}
