//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Firmen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Firmen()
        {
            this.tbl_ProjektFirmaRel = new HashSet<tbl_ProjektFirmaRel>();
        }
    
        public int FirmaNr { get; set; }
        public string Firma { get; set; }
        public string ImdbID { get; set; }
        public Nullable<int> Companymeter { get; set; }
        public string Job { get; set; }
        public string Matchname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjektFirmaRel> tbl_ProjektFirmaRel { get; set; }
    }
}
