//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Regisseure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Regisseure()
        {
            this.tbl_Projekte = new HashSet<tbl_Projekte>();
        }
    
        public int RegisseurNr { get; set; }
        public string Nachname { get; set; }
        public string Vorname { get; set; }
        public string Werke { get; set; }
        public string Regie { get; set; }
        public string Matchname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Projekte> tbl_Projekte { get; set; }
    }
}
