//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Projekte
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Projekte()
        {
            this.ProjektartNr = 1;
            this.FormatNr = 1;
            this.tbl_ProjektAuswertungsArtRel = new HashSet<tbl_ProjektAuswertungsArtRel>();
            this.tbl_ProjektPersonRel = new HashSet<tbl_ProjektPersonRel>();
            this.tbl_ProjektGenreRel = new HashSet<tbl_ProjektGenreRel>();
            this.tbl_ProjektLandRel = new HashSet<tbl_ProjektLandRel>();
            this.tbl_ProjektFirmaRel = new HashSet<tbl_ProjektFirmaRel>();
            this.tbl_Themen = new HashSet<tbl_Themen>();
            this.tbl_TV_Einschaetzung = new HashSet<tbl_TV_Einschaetzung>();
            this.tbl_Links = new HashSet<tbl_Links>();
            this.tbl_BlobData = new HashSet<tbl_BlobData>();
            this.tbl_WarenkorbProjektRel = new HashSet<tbl_WarenkorbProjektRel>();
            this.tbl_Bearbeiter1 = new HashSet<tbl_Bearbeiter>();
        }
    
        public int ENTRY_No { get; set; }
        public string Land { get; set; }
        public int AnbieterNr { get; set; }
        public string Kontakt { get; set; }
        public Nullable<System.DateTime> DATUM_ANGEBOT { get; set; }
        public string TITEL_PROJEKT_FILM { get; set; }
        public int StatusNr { get; set; }
        public string Rating { get; set; }
        public string Kurzbemerkung { get; set; }
        public Nullable<int> RegisseurNr { get; set; }
        public string Produzenten { get; set; }
        public string Produktionsfirma { get; set; }
        public string Script_Buch { get; set; }
        public string Drehbeginn { get; set; }
        public string Lieferbar { get; set; }
        public string Geschichte { get; set; }
        public string Asking { get; set; }
        public string Angebot { get; set; }
        public string Sonstiges { get; set; }
        public string Besetzung { get; set; }
        public string Budget { get; set; }
        public string US_Release { get; set; }
        public string Beurteilung { get; set; }
        public Nullable<System.DateTime> aktualisiert { get; set; }
        public bool Festival_akt { get; set; }
        public string ImdbNr { get; set; }
        public string Historie { get; set; }
        public string TV_Einschaetzung_Kommentar { get; set; }
        public string Koproduktionseinschaetzung { get; set; }
        public Nullable<decimal> BudgetX { get; set; }
        public int BudgetWE { get; set; }
        public string Budget_Kommentar { get; set; }
        public Nullable<decimal> AskingX { get; set; }
        public int AskingWE { get; set; }
        public bool Leseliste { get; set; }
        public bool Prioliste { get; set; }
        public bool Sichtung { get; set; }
        public int BearbeiterNr { get; set; }
        public int ProjektartNr { get; set; }
        public int LENr { get; set; }
        public int verkauft_an { get; set; }
        public bool alter_Standard { get; set; }
        public Nullable<int> Kopien { get; set; }
        public Nullable<decimal> PandA { get; set; }
        public Nullable<decimal> Backing { get; set; }
        public int BackingWE { get; set; }
        public Nullable<decimal> AngebotX { get; set; }
        public int AngebotWE { get; set; }
        public Nullable<decimal> Admission { get; set; }
        public Nullable<int> Age_Rating { get; set; }
        public string MPAA { get; set; }
        public string Age_Rating_Kommentar { get; set; }
        public string Originaltitel { get; set; }
        public System.DateTime aufgenommen_am { get; set; }
        public string geaendert_von { get; set; }
        public string Beurteilung_Lektor { get; set; }
        public bool AskingGSE { get; set; }
        public Nullable<decimal> AskingSchweiz { get; set; }
        public bool AngebotGSE { get; set; }
        public Nullable<decimal> AngebotSchweiz { get; set; }
        public Nullable<decimal> Kaufpreis { get; set; }
        public int KaufpreisWE { get; set; }
        public bool KaufpreisGSE { get; set; }
        public Nullable<decimal> KaufpreisSchweiz { get; set; }
        public bool Archiv { get; set; }
        public bool Produktionsliste { get; set; }
        public Nullable<System.DateTime> Erinnerung { get; set; }
        public string Erinnerung_an { get; set; }
        public string Synopsis { get; set; }
        public int FormatNr { get; set; }
        public int BearbeiterNr2 { get; set; }
        public int AnbieterNr2 { get; set; }
    
        public virtual tbl_Anbieter tbl_Anbieter { get; set; }
        public virtual tbl_Bearbeiter tbl_Bearbeiter { get; set; }
        public virtual tbl_Lektoratseinschaetzung tbl_Lektoratseinschaetzung { get; set; }
        public virtual tbl_Projektart tbl_Projektart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjektAuswertungsArtRel> tbl_ProjektAuswertungsArtRel { get; set; }
        public virtual tbl_WE tbl_AskingWE { get; set; }
        public virtual tbl_WE tbl_BudgetWE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjektPersonRel> tbl_ProjektPersonRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjektGenreRel> tbl_ProjektGenreRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjektLandRel> tbl_ProjektLandRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjektFirmaRel> tbl_ProjektFirmaRel { get; set; }
        public virtual tbl_Verleih tbl_Verleih { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Themen> tbl_Themen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TV_Einschaetzung> tbl_TV_Einschaetzung { get; set; }
        public virtual tbl_Rating tbl_Rating { get; set; }
        public virtual tbl_Regisseure tbl_Regisseure { get; set; }
        public virtual tbl_Status tbl_Status { get; set; }
        public virtual tbl_WE tbl_AngebotWE { get; set; }
        public virtual tbl_WE tbl_BackingWE { get; set; }
        public virtual tbl_BlobProjekte tbl_BlobProjekte { get; set; }
        public virtual tbl_WE tbl_KaufpreisWE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Links> tbl_Links { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BlobData> tbl_BlobData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_WarenkorbProjektRel> tbl_WarenkorbProjektRel { get; set; }
        public virtual tbl_Filmformate tbl_Filmformate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Bearbeiter> tbl_Bearbeiter1 { get; set; }
        public virtual tbl_Anbieter tbl_Anbieter1 { get; set; }
        public virtual tbl_Bearbeiter tbl_Bearbeiter11 { get; set; }
    }
}
