//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efAkquisition
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Personen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Personen()
        {
            this.tbl_ProjektPersonRel = new HashSet<tbl_ProjektPersonRel>();
        }
    
        public int PersonNr { get; set; }
        public string Name { get; set; }
        public string ImdbID { get; set; }
        public Nullable<int> Starmeter { get; set; }
        public string Filme { get; set; }
        public int JobOne { get; set; }
        public int JobTwo { get; set; }
        public int JobThree { get; set; }
        public string Matchname { get; set; }
        public bool IsFirma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProjektPersonRel> tbl_ProjektPersonRel { get; set; }
        public virtual tbl_Jobs tbl_Jobs1 { get; set; }
        public virtual tbl_Jobs tbl_Jobs3 { get; set; }
        public virtual tbl_Jobs tbl_Jobs2 { get; set; }
    }
}
